### ISSUE TITLE
Create minimal SDK

### ISSUE THREAD

**Issue by petrbel** [iterait/shepherd#53]
Let's start on tomorrow :)

**Comment by blazekadam** [comment]
:+1: looking forward to this

**Comment by petrbel** [comment]
@blazekadam github isn't facebook, bro :D

**Comment by blazekadam** [comment]
@petrbel It is quite common to express your support for a particular issue (or rather feature request) with a :+1: , I can provide you with some examples from well-established github projects if you want ...

**Comment by blazekadam** [comment]
bro...

**Comment by blazekadam** [comment]
The sdk project should be referenced in readme btw.
